version:2

jobs:
  shama_test_case:
     docker:
         - image: circleci/node:lts
    working_directory: ~/repo
    steps: 
        - checkout
        - run : 
            name: Install Deps
            command: yarn
